version: '3.8'

services:
  api-ami-files:
    image: extrimianpublic.azurecr.io/api-ami-files:0.0.2
    ports:
      - "8000:8000"
    environment:
      - ACCOUNT_NAME=amifiles-proyecto-a
      - ACCOUNT_KEY=****
      - BLOB_SERVICE_URL=https://amifiles-proyecto-a.blob.core.windows.net
      - API_SERVICE_URL=https://amifiles.proyecto-a.com


  
